from .studentProfileCreateSerializer import StudentProfileCreateSerializer
from .studentProfileListSerializer import StudentProfileListSerializer
from .studentProfileUpdateSerializer import StudentProfileUpdateSerializer
from .studentProfileRetrieveSerializer import StudentProfileRetrieveSerializer