# Generated by Django 4.2.5 on 2023-10-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="phone",
            new_name="phone_no",
        ),
    ]
