# Generated by Django 4.2.5 on 2023-10-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="placement",
            name="supervisor_phone_no",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
