# Generated by Django 4.2.5 on 2023-10-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="duration",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vacancy",
            name="industry",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
