# Generated by Django 4.2.3 on 2023-08-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="created_at",
            new_name="craeted_at",
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
