# Generated by Django 4.2.5 on 2023-11-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0002_vacancy_duration_vacancy_industry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_student",
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
