# Generated by Django 4.2.3 on 2023-09-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0002_feedback"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("student_profile", "internship")},
        ),
    ]
