# Generated by Django 4.2.5 on 2023-11-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0003_remove_user_is_student_delete_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="craeted_at",
            new_name="created_at",
        ),
    ]
