# Generated by Django 4.2.3 on 2023-09-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0003_alter_application_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
