# Generated by Django 4.2.3 on 2023-09-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0004_application_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_organization_user",
            field=models.BooleanField(default=False),
        ),
    ]
