# Generated by Django 4.2.5 on 2023-11-22 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0004_rename_craeted_at_user_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
    ]
