# Generated by Django 4.2.3 on 2023-09-30 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0005_user_is_organization_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_common.organization",
            ),
            preserve_default=False,
        ),
    ]
