# Generated by Django 4.2.5 on 2023-11-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0005_remove_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "male"), ("F", "female"), ("O", "other")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
