# Generated by Django 4.2.5 on 2023-11-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0006_user_gender_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(default="M", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organization",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="alt_phone_no",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="industry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_documents",
            field=models.FileField(
                blank=True, null=True, upload_to="organization_documents"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="phone_no",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="alt_phone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="git_hub",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_no",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="student",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="university",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
