# Generated by Django 4.2.3 on 2023-09-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0006_application_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="organization",
        ),
    ]
