# Generated by Django 4.2.5 on 2023-11-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "auth_common",
            "0007_student_first_name_student_gender_student_last_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="cover_letter",
        ),
        migrations.RemoveField(
            model_name="application",
            name="resume",
        ),
    ]
