# Generated by Django 4.2.3 on 2023-09-30 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0007_remove_application_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_common.organization",
            ),
        ),
    ]
