# Generated by Django 4.2.5 on 2023-11-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0008_remove_application_cover_letter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(default="pending", max_length=255),
        ),
    ]
