# Generated by Django 4.2.3 on 2023-09-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0008_application_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_organization_user",
        ),
    ]
