# Generated by Django 4.2.5 on 2023-11-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0009_alter_application_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="benefits",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="compensation",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="experience_level",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="qualifications",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="responsibilities",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="title",
        ),
        migrations.AddField(
            model_name="organization",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="job_type",
            field=models.CharField(max_length=20),
        ),
    ]
