# Generated by Django 4.2.5 on 2023-11-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auth_common",
            "0010_remove_vacancy_benefits_remove_vacancy_compensation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="placement",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
