# Generated by Django 4.2.5 on 2023-11-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0012_vacancy_banner_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="negotiable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary",
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
