# Generated by Django 4.2.5 on 2023-11-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auth_common",
            "0015_remove_vacancy_negotiable_alter_vacancy_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="requirements",
            field=models.TextField(),
        ),
    ]
