# Generated by Django 4.2.5 on 2023-11-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0016_alter_vacancy_description_alter_vacancy_requirements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="requirements",
            field=models.CharField(max_length=2000),
        ),
    ]
