# Generated by Django 4.2.5 on 2023-11-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0017_alter_vacancy_description_alter_vacancy_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="negotiable",
            field=models.BooleanField(default=False),
        ),
    ]
