# Generated by Django 4.2.5 on 2023-11-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0018_vacancy_negotiable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="negotiable",
        ),
    ]
