# Generated by Django 4.2.5 on 2023-11-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0019_remove_vacancy_negotiable"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
