# Generated by Django 4.2.5 on 2023-11-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_common", "0020_organization_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="organization_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="student_photos/"),
        ),
    ]
